name: myflake

on:
  push:
    branches:
      - main
    paths:
      - 'snowflake/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Snowflake Connector
      run: |
        pip install snowflake-connector-python

    - name: Check location
      run: ls -l /bin

    - name: check lib
      run: ls -l /usr/local/bin

    # - name: Execute SQL Script
    #   run: |
    #     for file in snowflake/*.sql; do
    #        snowsql -a $SNOWFLAKE_ACCOUNT -u $SNOWFLAKE_USERNAME -d $SNOWFLAKE_DATABASE -s PUBLIC -w $SNOWFLAKE_WAREHOUSE -r $SNOWFLAKE_ROLE -f $file
    #     done
    #   env:
    #     SNOWFLAKE_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
    #     SNOWFLAKE_USERNAME: ${{ secrets.SF_USERNAME }}
    #     SNOWFLAKE_DATABASE: ${{ secrets.SF_DATABASE }}
    #     #SNOWFLAKE_SCHEMA: ${{ secrets.SF_SCHEMA }}
    #     SNOWFLAKE_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
    #     SNOWFLAKE_ROLE: ${{ secrets.SF_ROLE }}
