name: myflake

on:
  push:
    branches:
      - main
    paths:
      - 'snowflake/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Snowflake Connector
      run: |
        pip install snowflake-connector-python

    - name: Download SnowSQL
      run:  curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.9-linux_x86_64.bash
    - name: Install SnowSQL
      run:  SNOWSQL_DEST=~/bin SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.2.9-linux_x86_64.bash
    - name: Show Version
      run:  ~/bin/snowsql -v

    - name: Execute SQL Script
      run: |
        for file in snowflake/*.sql; do
           ~/bin/snowsql -a $SNOWFLAKE_ACCOUNT -u $SNOWFLAKE_USERNAME -d $SNOWFLAKE_DATABASE -s PUBLIC -w $SNOWFLAKE_WAREHOUSE -r $SNOWFLAKE_ROLE -f $file
        done
      env:
        SNOWFLAKE_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
        SNOWFLAKE_USERNAME: ${{ secrets.SF_USERNAME }}
        SNOWFLAKE_DATABASE: ${{ secrets.SF_DATABASE }}
        #SNOWFLAKE_SCHEMA: ${{ secrets.SF_SCHEMA }}
        SNOWFLAKE_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
        SNOWFLAKE_ROLE: ${{ secrets.SF_ROLE }}
