name: Copy AWS SnowFlake

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.3
      - name: Install AWS cli
        run: apt-get --assume-yes install awscli

      - name: Configure AWS Credentials
        run: |
          echo "[default]
          aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_default_region = ${{ secrets.AWS_REGION }}" > ~/.aws/credentials
      - name: Set AWS CLI Configuration
        run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && aws configure set default.region ${{ secrets.AWS_REGION }}
      
      - name: Copy files
        run: |
          aws s3 cp githu.csv s3://cross-snwoflake-test/
      
