name: MY 

on:
  push:
    branches:
      - main
    paths:
      - 'snowflake/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Snowflake Connector
        run: |
          python -m pip install --upgrade pip
          pip install snowflake-connector-python

      - name: Execute SQL Scripts
        run: |
          for file in snowflake/*.sql; do
            snowsql -a $SNOWFLAKE_ACCOUNT -u $SNOWFLAKE_USER -p $SNOWFLAKE_PASSWORD \
                    -w $SNOWFLAKE_WAREHOUSE -d $SNOWFLAKE_DATABASE -s PUBLIC \
                    -f $file
          done
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SF_USERNAME }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
          SNOWFLAKE_DATABASE: ${{ secrets.SF_DATABASE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
