name: SnowSQL
env:
  
  SNOWSQL_ACCOUNT: OOZELMY.LXB06506
  SNOWSQL_USER: dhanabaloptisol
  SNOWSQL_PWD: ${{ secrets.SF_PASSWORD }}
  
on:
  push:
    branches:
      - main
    paths:
      - 'snowflake/**'
  workflow_dispatch:
jobs:                         
  executequery:                           
    name: Install SnowSQL                          
    runs-on: ubuntu-latest                           
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Download SnowSQL
      run:  curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.9-linux_x86_64.bash
    - name: Install SnowSQL
      run: SNOWSQL_DEST=~/bin SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.2.9-linux_x86_64.bash
    - name: Test installation
      run:  ~/bin/snowsql -v
    - name: Execute SQL against Snowflake
      run:  ~/bin/snowsql -f snowflake/V1.1.1__initial_objects.sql;
