name: Check Internet Connectivity

on:
  push:
    branches:
      - main

jobs:
  check-connectivity:
    runs-on: ubuntu-latest

    steps:
    - name: Check Internet Connectivity
      run: |
        wget -q --spider https://www.google.com

        # Check the exit code of the wget command
        if [ $? -eq 0 ]; then
          echo "Internet connectivity is available."
        else
          echo "Internet connectivity is not available."
        fi
